name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2
    - uses: actions/setup-go@v4

    - name: Install deps
      run: ./resources/install_deps.sh

    - name: Build
      run: |
        git submodule update --recursive --init
        ./resources/build.sh

    - name: Test build
      run: ./resources/test.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          *.AppImage
          *.shImg
          *.zsync
          *.a
          *.so
          *.h
          profile_database.json
